package provider

const failedToUpdateUserPermissions = "Failed to update user permissions"
const failedToRemoveUserPermissions = "Failed to remove user permissions"
const failedToUpdateGroupPermissions = "Failed to update group permissions"
const failedToRemoveGroupPermissions = "Failed to remove group permissions"

const errorProvidedRepositoryMustBeNumber = "Provided repository must be a number"
const errorProvidedDeploymentIdMustBeNumber = "Provided ID must be a number"
const errorFailedToReadDeployment = "Failed to read deployment"
const errorFailedToAddDeployment = "Failed to add deployment"
const errorFailedToReadRepository = "Failed to read repository"
const errorFailedToAddRepository = "Failed to add repository"
const errorFailedToRemoveRepository = "Failed to remove repository"
const errorFailedToUpdateRepository = "Failed to update repository"
const errorFailedToAddProjectRepositories = "Failed to add project repositories"
const errorFailedToRemoveProjectRepositories = "Failed to remove project repositories"
const errorFailedToReadRepositoryAccessor = "Failed to read repository accessor"
const errorFailedToAddRepositoryAccessor = "Failed to add repository accessor"
const errorFailedToRemoveRepositoryAccessor = "Failed to remove repository accessor"
